[2023-05-14 09:34:25 +0800] [1465811] [INFO] Starting gunicorn 20.0.4
[2023-05-14 09:34:25 +0800] [1465811] [INFO] Listening at: http://0.0.0.0:56100 (1465811)
[2023-05-14 09:34:25 +0800] [1465811] [INFO] Using worker: sync
[2023-05-14 09:34:25 +0800] [1465813] [INFO] Booting worker with pid: 1465813
[2023-05-15 23:15:03 +0800] [1465811] [INFO] Handling signal: term
[2023-05-15 23:15:03 +0800] [1465813] [INFO] Worker exiting (pid: 1465813)
https://cpmp.ebg.tw/api/oauth
{'Authorization': 'Bearer r996fddp35sI3QjB2jfsbKYx5yyIib'}
[2023-05-15 23:15:03 +0800] [1465811] [INFO] Shutting down: Master
[2023-05-19 02:01:11 +0800] [3859869] [INFO] Starting gunicorn 20.0.4
[2023-05-19 02:01:11 +0800] [3859869] [INFO] Listening at: http://0.0.0.0:56100 (3859869)
[2023-05-19 02:01:11 +0800] [3859869] [INFO] Using worker: sync
[2023-05-19 02:01:11 +0800] [3859871] [INFO] Booting worker with pid: 3859871
[2023-05-19 02:41:45,210] ERROR in app: Exception on /api/logout [GET]
Traceback (most recent call last):
  File "/home/darkknive/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/darkknive/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/darkknive/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/darkknive/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/darkknive/codes/1112DBMS/backend/server.py", line 38, in logout
    session.unbind(flask.request.environ['session'])
  File "/home/darkknive/codes/1112DBMS/backend/session.py", line 27, in unbind
    del tmp_sql[session]
KeyError: 'ed4f63103b1749fdb26c3aa246179e51'
[2023-05-19 02:41:49,119] ERROR in app: Exception on /api/logout [GET]
Traceback (most recent call last):
  File "/home/darkknive/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/darkknive/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/darkknive/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/darkknive/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/darkknive/codes/1112DBMS/backend/server.py", line 38, in logout
    session.unbind(flask.request.environ['session'])
  File "/home/darkknive/codes/1112DBMS/backend/session.py", line 27, in unbind
    del tmp_sql[session]
KeyError: 'f05d182b184041cf892ecddd4ccd6ccd'
[2023-05-19 03:21:28 +0800] [3859869] [INFO] Handling signal: term
[2023-05-19 03:21:28 +0800] [3859871] [INFO] Worker exiting (pid: 3859871)
https://cpmp.ebg.tw/api/oauth
https://cpmp.ebg.tw/api/oauth
https://cpmp.ebg.tw/api/oauth
[2023-05-19 03:21:28 +0800] [3859869] [INFO] Shutting down: Master
[2023-05-19 03:35:39 +0800] [4009298] [INFO] Starting gunicorn 20.0.4
[2023-05-19 03:35:39 +0800] [4009298] [INFO] Listening at: http://0.0.0.0:56100 (4009298)
[2023-05-19 03:35:39 +0800] [4009298] [INFO] Using worker: sync
[2023-05-19 03:35:39 +0800] [4009300] [INFO] Booting worker with pid: 4009300
[2023-05-19 20:11:30 +0800] [4009298] [INFO] Handling signal: term
[2023-05-19 20:11:30 +0800] [4009300] [INFO] Worker exiting (pid: 4009300)
https://cpmp.ebg.tw/api/oauth
[2023-05-19 20:11:30 +0800] [4009298] [INFO] Shutting down: Master
[2023-05-20 12:22:38 +0800] [2936546] [INFO] Starting gunicorn 20.0.4
[2023-05-20 12:22:38 +0800] [2936546] [INFO] Listening at: http://0.0.0.0:56100 (2936546)
[2023-05-20 12:22:38 +0800] [2936546] [INFO] Using worker: sync
[2023-05-20 12:22:38 +0800] [2936548] [INFO] Booting worker with pid: 2936548
[2023-05-21 17:58:23 +0800] [2936546] [INFO] Handling signal: term
[2023-05-21 17:58:23 +0800] [2936548] [INFO] Worker exiting (pid: 2936548)
https://cpmp.ebg.tw/api/oauth
http://localhost:3000/oauthCallback
http://localhost:3000/oauthCallback
https://cpmp.ebg.tw/api/oauth
https://cpmp.ebg.tw/api/oauth
[2023-05-21 17:58:23 +0800] [2936546] [INFO] Shutting down: Master
[2023-05-22 00:42:39 +0800] [2256362] [INFO] Starting gunicorn 20.0.4
[2023-05-22 00:42:39 +0800] [2256362] [INFO] Listening at: http://0.0.0.0:56100 (2256362)
[2023-05-22 00:42:39 +0800] [2256362] [INFO] Using worker: sync
[2023-05-22 00:42:39 +0800] [2256364] [INFO] Booting worker with pid: 2256364
[2023-05-22 17:26:26 +0800] [3865433] [INFO] Starting gunicorn 20.0.4
[2023-05-22 17:26:26 +0800] [3865433] [ERROR] Connection in use: ('0.0.0.0', 56100)
[2023-05-22 17:26:26 +0800] [3865433] [ERROR] Retrying in 1 second.
[2023-05-22 17:26:27 +0800] [3865433] [ERROR] Connection in use: ('0.0.0.0', 56100)
[2023-05-22 17:26:27 +0800] [3865433] [ERROR] Retrying in 1 second.
[2023-05-22 17:26:28 +0800] [3865433] [ERROR] Connection in use: ('0.0.0.0', 56100)
[2023-05-22 17:26:28 +0800] [3865433] [ERROR] Retrying in 1 second.
[2023-05-22 17:26:29 +0800] [3865433] [ERROR] Connection in use: ('0.0.0.0', 56100)
[2023-05-22 17:26:29 +0800] [3865433] [ERROR] Retrying in 1 second.
[2023-05-22 17:26:30 +0800] [3865433] [ERROR] Connection in use: ('0.0.0.0', 56100)
[2023-05-22 17:26:30 +0800] [3865433] [ERROR] Retrying in 1 second.
[2023-05-22 17:26:31 +0800] [3865433] [ERROR] Can't connect to ('0.0.0.0', 56100)
[2023-05-22 17:30:16 +0800] [2256362] [INFO] Handling signal: term
[2023-05-22 17:30:16 +0800] [2256364] [INFO] Worker exiting (pid: 2256364)
https://cpmp.ebg.tw/api/oauth
http://localhost:3000/oauthCallback
https://cpmp.ebg.tw/oauthCallback
https://cpmp.ebg.tw/oauthCallback
http://localhost:3000/oauthCallback
http://localhost:3000/oauthCallback
http://localhost:3000/oauthCallback
http://localhost:3000/oauthCallback
http://localhost:3000/oauthCallback
http://localhost:3000/oauthCallback
http://localhost:3000/oauthCallback
http://localhost:3000/oauthCallback
https://cpmp.ebg.tw/oauthCallback
https://cpmp.ebg.tw/oauthCallback
https://cpmp.ebg.tw/oauthCallback
[2023-05-22 17:30:16 +0800] [2256362] [INFO] Shutting down: Master
[2023-05-22 17:30:20 +0800] [3871583] [INFO] Starting gunicorn 20.0.4
[2023-05-22 17:30:20 +0800] [3871583] [INFO] Listening at: http://0.0.0.0:56100 (3871583)
[2023-05-22 17:30:20 +0800] [3871583] [INFO] Using worker: sync
[2023-05-22 17:30:20 +0800] [3871585] [INFO] Booting worker with pid: 3871585
[2023-05-22 17:30:20 +0800] [3871585] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 383, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/darkknive/codes/1112DBMS/backend/run.py", line 1, in <module>
    from server import app
  File "/home/darkknive/codes/1112DBMS/backend/server.py", line 78
    "error": False
           ^
SyntaxError: invalid syntax
[2023-05-22 17:30:20 +0800] [3871585] [INFO] Worker exiting (pid: 3871585)
[2023-05-22 17:30:20 +0800] [3871583] [INFO] Shutting down: Master
[2023-05-22 17:30:20 +0800] [3871583] [INFO] Reason: Worker failed to boot.
[2023-05-22 17:30:44 +0800] [3872301] [INFO] Starting gunicorn 20.0.4
[2023-05-22 17:30:44 +0800] [3872301] [INFO] Listening at: http://0.0.0.0:56100 (3872301)
[2023-05-22 17:30:44 +0800] [3872301] [INFO] Using worker: sync
[2023-05-22 17:30:44 +0800] [3872314] [INFO] Booting worker with pid: 3872314
[2023-05-22 17:30:44 +0800] [3872314] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 383, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/darkknive/codes/1112DBMS/backend/run.py", line 1, in <module>
    from server import app
  File "/home/darkknive/codes/1112DBMS/backend/server.py", line 78
    "error": False
           ^
SyntaxError: invalid syntax
[2023-05-22 17:30:44 +0800] [3872314] [INFO] Worker exiting (pid: 3872314)
[2023-05-22 17:30:44 +0800] [3872301] [INFO] Shutting down: Master
[2023-05-22 17:30:44 +0800] [3872301] [INFO] Reason: Worker failed to boot.
[2023-05-22 17:31:14 +0800] [3873014] [INFO] Starting gunicorn 20.0.4
[2023-05-22 17:31:14 +0800] [3873014] [INFO] Listening at: http://0.0.0.0:56100 (3873014)
[2023-05-22 17:31:14 +0800] [3873014] [INFO] Using worker: sync
[2023-05-22 17:31:14 +0800] [3873016] [INFO] Booting worker with pid: 3873016
[2023-05-22 18:24:16 +0800] [3873014] [INFO] Handling signal: term
[2023-05-22 18:24:16 +0800] [3873016] [INFO] Worker exiting (pid: 3873016)
https://cpmp.ebg.tw/oauthCallback
https://cpmp.ebg.tw/oauthCallback
[2023-05-22 18:24:16 +0800] [3873014] [INFO] Shutting down: Master
[2023-05-22 21:47:45 +0800] [83207] [INFO] Starting gunicorn 20.0.4
[2023-05-22 21:47:45 +0800] [83207] [INFO] Listening at: http://0.0.0.0:56100 (83207)
[2023-05-22 21:47:45 +0800] [83207] [INFO] Using worker: sync
[2023-05-22 21:47:45 +0800] [83247] [INFO] Booting worker with pid: 83247
[2023-05-22 21:53:34 +0800] [83207] [INFO] Handling signal: term
[2023-05-22 21:53:34 +0800] [83247] [INFO] Worker exiting (pid: 83247)
referrer: None
URL: https://cpmp.ebg.tw/api/500
referrer: None
URL: https://cpmp.ebg.tw/api/500
[2023-05-22 21:53:34 +0800] [83207] [INFO] Shutting down: Master
[2023-05-23 05:18:34 +0800] [798129] [INFO] Starting gunicorn 20.0.4
[2023-05-23 05:18:34 +0800] [798129] [INFO] Listening at: http://0.0.0.0:56100 (798129)
[2023-05-23 05:18:34 +0800] [798129] [INFO] Using worker: sync
[2023-05-23 05:18:34 +0800] [798131] [INFO] Booting worker with pid: 798131
referrer: https://cpmp.ebg.tw/
URL: https://cpmp.ebg.tw/api/profile
referrer: https://cpmp.ebg.tw/oauthCallback?code=HHHf9fS7jTwoG8M9EHxsbU2Ov3I8Pa&state=15773059ghq9183habn
URL: https://cpmp.ebg.tw/api/oauth
https://cpmp.ebg.tw/oauthCallback
{'id': '596917442286977072', 'username': 'andyjjrt', 'global_name': None, 'avatar': '667c41e9f1076e47e9189a16dd49cf2a', 'discriminator': '0710', 'public_flags': 256, 'flags': 256, 'banner': 'a_ff266a96fef38e4b7fae59b6aa192f7d', 'banner_color': '#fa9090', 'accent_color': 16421008, 'locale': 'zh-TW', 'mfa_enabled': True, 'premium_type': 2, 'avatar_decoration': 'v3_a_9cd7e573f48859a995266a0a8345f336', 'email': 'andyjjrt@gmail.com', 'verified': True}
{'id': '596917442286977072', 'username': 'andyjjrt', 'global_name': None, 'avatar': '667c41e9f1076e47e9189a16dd49cf2a', 'discriminator': '0710', 'public_flags': 256, 'flags': 256, 'banner': 'a_ff266a96fef38e4b7fae59b6aa192f7d', 'banner_color': '#fa9090', 'accent_color': 16421008, 'locale': 'zh-TW', 'mfa_enabled': True, 'premium_type': 2, 'avatar_decoration': 'v3_a_9cd7e573f48859a995266a0a8345f336', 'email': 'andyjjrt@gmail.com', 'verified': True}
referrer: https://cpmp.ebg.tw/
URL: https://cpmp.ebg.tw/api/profile
referrer: https://cpmp.ebg.tw/
URL: https://cpmp.ebg.tw/api/profile
referrer: https://cpmp.ebg.tw/
URL: https://cpmp.ebg.tw/api/profile
referrer: https://cpmp.ebg.tw/
URL: https://cpmp.ebg.tw/api/profile
referrer: https://cpmp.ebg.tw/
URL: https://cpmp.ebg.tw/api/profile
referrer: https://cpmp.ebg.tw/
URL: https://cpmp.ebg.tw/api/profile
referrer: https://cpmp.ebg.tw/
URL: https://cpmp.ebg.tw/api/profile
referrer: https://cpmp.ebg.tw/search?keyword=%E6%95%85%E5%9F%8E%E5%BE%80%E4%BA%8B
URL: https://cpmp.ebg.tw/api/search
offset: 0
length: 10
len = 18
Unexpected renderer encountered.
Renderer name: dict_keys(['reelShelfRenderer'])
Search term: 強風
Please open an issue at https://github.com/pytube/pytube/issues and provide this log output.
Unexpected renderer encountered.
Renderer name: dict_keys(['reelShelfRenderer'])
Search term: 強風
Please open an issue at https://github.com/pytube/pytube/issues and provide this log output.
referrer: https://cpmp.ebg.tw/search?keyword=%E5%BC%B7%E9%A2%A8
URL: https://cpmp.ebg.tw/api/search
offset: 0
length: 10
len = 20
Unexpected renderer encountered.
Renderer name: dict_keys(['reelShelfRenderer'])
Search term: 強風
Please open an issue at https://github.com/pytube/pytube/issues and provide this log output.
Unexpected renderer encountered.
Renderer name: dict_keys(['reelShelfRenderer'])
Search term: 強風
Please open an issue at https://github.com/pytube/pytube/issues and provide this log output.
referrer: https://cpmp.ebg.tw/oauthCallback?code=SEgET300Vadjfx9IsAg17RwUI5RXiR&state=15773059ghq9183habn
URL: https://cpmp.ebg.tw/api/oauth
https://cpmp.ebg.tw/oauthCallback
{'id': '391837295612919818', 'username': 'Terminus_Est.', 'global_name': None, 'avatar': '401ce50cba9c7eb821a7a052ff243dca', 'discriminator': '1337', 'public_flags': 0, 'flags': 0, 'banner': '5fc895d1d85ac64aa76889f36b9542be', 'banner_color': None, 'accent_color': None, 'locale': 'zh-TW', 'mfa_enabled': True, 'premium_type': 2, 'avatar_decoration': None, 'email': 'asdfg3655@yahoo.com.tw', 'verified': True}
{'id': '391837295612919818', 'username': 'Terminus_Est.', 'global_name': None, 'avatar': '401ce50cba9c7eb821a7a052ff243dca', 'discriminator': '1337', 'public_flags': 0, 'flags': 0, 'banner': '5fc895d1d85ac64aa76889f36b9542be', 'banner_color': None, 'accent_color': None, 'locale': 'zh-TW', 'mfa_enabled': True, 'premium_type': 2, 'avatar_decoration': None, 'email': 'asdfg3655@yahoo.com.tw', 'verified': True}
referrer: https://cpmp.ebg.tw/search?keyword=%E5%BC%B7%E9%A2%A8
URL: https://cpmp.ebg.tw/api/search
offset: 0
length: 10
len = 20
Unexpected renderer encountered.
Renderer name: dict_keys(['movieRenderer'])
Search term: 打上花火
Please open an issue at https://github.com/pytube/pytube/issues and provide this log output.
referrer: https://cpmp.ebg.tw/search?keyword=%E5%BC%B7%E9%A2%A8
URL: https://cpmp.ebg.tw/api/profile
referrer: None
URL: https://cpmp.ebg.tw/api/login
referrer: https://cpmp.ebg.tw/api/login
URL: https://cpmp.ebg.tw/api/logout
referrer: None
URL: https://cpmp.ebg.tw/api/login
referrer: None
URL: https://cpmp.ebg.tw/api/login
referrer: https://discord.com/
URL: https://cpmp.ebg.tw/api/oauth
https://cpmp.ebg.tw/api/oauth
{'id': '391837295612919818', 'username': 'Terminus_Est.', 'global_name': None, 'avatar': '401ce50cba9c7eb821a7a052ff243dca', 'discriminator': '1337', 'public_flags': 0, 'flags': 0, 'banner': '5fc895d1d85ac64aa76889f36b9542be', 'banner_color': None, 'accent_color': None, 'locale': 'zh-TW', 'mfa_enabled': True, 'premium_type': 2, 'avatar_decoration': None, 'email': 'asdfg3655@yahoo.com.tw', 'verified': True}
referrer: None
URL: https://cpmp.ebg.tw/api/login
referrer: https://cpmp.ebg.tw/search?keyword=%E6%89%93%E4%B8%8A%E8%8A%B1%E7%81%AB
URL: https://cpmp.ebg.tw/api/search
offset: 0
length: 10
len = 18
